blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/jz8T2uahpH
    about: Quick questions, sharing a video of a bug, or anything that's better as a chat. A lot of issues start better here.
